# joint_limits.yaml for xArm 6 - allows dynamics properties specified in URDF to be overwritten

# Conservative scaling factors for safe operation
default_velocity_scaling_factor: 0.2
default_acceleration_scaling_factor: 0.2

# Specific joint properties
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28
  joint2:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_position_limits: true
    min_position: -2.09
    max_position: 2.09
  joint3:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28
  joint4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28
  joint5:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_position_limits: true
    min_position: -1.69
    max_position: 3.84
  joint6:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28